# =======================================================================
# modules/compute/main.tf
#
# Creates: Static Public IP, NIC, Ubuntu 22.04 LTS Linux VM
#
# KEY CHANGE FROM SCENARIO 6:
# SSH key authentication via a local key file is removed.
# The AADSSHLoginForLinux extension is added so users authenticate
# via Azure AD (az ssh vm ...) instead of a private key.
# A throw-away TLS keypair is generated by Terraform purely because the
# Azure API requires at least one SSH key on Linux VMs. This key is never
# handed to any human — it lives only in Terraform state.
# The azurerm_role_assignment grants the specified Azure AD user the
# "Virtual Machine Administrator Login" role so they can actually connect.
# =======================================================================

# Throw-away keypair — satisfies Azure API requirement, never used by humans
resource "tls_private_key" "vm_key" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "azurerm_public_ip" "pip" {
  name                = "${var.vm_name}-pip"
  location            = var.location
  resource_group_name = var.resource_group_name
  allocation_method   = "Static"
  sku                 = "Standard"
  tags                = var.tags
}

resource "azurerm_network_interface" "nic" {
  name                = "${var.vm_name}-nic"
  location            = var.location
  resource_group_name = var.resource_group_name
  tags                = var.tags

  ip_configuration {
    name                          = "internal"
    subnet_id                     = var.subnet_id
    private_ip_address_allocation = "Dynamic"
    public_ip_address_id          = azurerm_public_ip.pip.id
  }
}

resource "azurerm_linux_virtual_machine" "vm" {
  name                  = var.vm_name
  location              = var.location
  resource_group_name   = var.resource_group_name
  size                  = var.vm_size
  admin_username        = var.admin_username
  network_interface_ids = [azurerm_network_interface.nic.id]
  tags                  = var.tags

  disable_password_authentication = true

  # Throw-away key — Azure requires this field, but AAD SSH is the real access method
  admin_ssh_key {
    username   = var.admin_username
    public_key = tls_private_key.vm_key.public_key_openssh
  }

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
    disk_size_gb         = 30
  }

  source_image_reference {
    publisher = "Canonical"
    offer     = "0001-com-ubuntu-server-jammy"
    sku       = "22_04-lts-gen2"
    version   = "latest"
  }
}

# -----------------------------------------------------------------------
# AAD SSH Extension
# Installs the agent on the VM that accepts Azure AD tokens for SSH.
# Without this, az ssh vm will fail even if the RBAC role is assigned.
# -----------------------------------------------------------------------
resource "azurerm_virtual_machine_extension" "aad_ssh" {
  name                 = "AADSSHLoginForLinux"
  virtual_machine_id   = azurerm_linux_virtual_machine.vm.id
  publisher            = "Microsoft.Azure.ActiveDirectory"
  type                 = "AADSSHLoginForLinux"
  type_handler_version = "1.0"
}

# -----------------------------------------------------------------------
# RBAC — grant the specified Azure AD user SSH access to this VM
#
# INTERVIEW TALKING POINT:
# "Access is controlled by RBAC, not by distributing SSH keys. Revoking
#  access means removing a role assignment — no key rotation, no hunting
#  down which laptops have a copy of the private key."
# -----------------------------------------------------------------------
resource "azurerm_role_assignment" "vm_admin_login" {
  scope                = azurerm_linux_virtual_machine.vm.id
  role_definition_name = "Virtual Machine Administrator Login"
  principal_id         = var.admin_object_id
}
